### PR TITLE
Home carousel

### PR DESCRIPTION
**Pull request by Pisotski**
TEAM:
horizontal scrolling is disabled

Implemented infinitely scrolling carousel using Framer.Motion

Added some semantically correct HTML for accessibility. That part isn't finished yet.

### CODE REVIEW

**Comment by CHEUNG-K-Jeffrey** [comment]
suggestion: rename pages folder to Pages

**Comment by CHEUNG-K-Jeffrey** [comment]
A git rebase may be required to fix it.

**Comment by CHEUNG-K-Jeffrey** [comment]
suggestion: rename the "pages" folder to "Pages" and git rebase it

**Comment by Pisotski** [comment]
> suggestion: rename the "pages" folder to "Pages" and git rebase it. It needs to be done on your end as the folder rename from pages to Pages doesn't work on case-insensitive file system.

that's interesting. it is upper case on local machine.

**Review by cartyz — APPROVED** [review]

**Pull request merged**
