### PR TITLE
feat: add ability to mock api and data

### PR DESCRIPTION
**Pull request by CHEUNG-K-Jeffrey**
Adds the software from [msw](https://mswjs.io/) for mocking an API.

### CODE REVIEW

**Comment by CHEUNG-K-Jeffrey** [comment]
suggestion: Need to add ways to disable mocking.

**Comment by CHEUNG-K-Jeffrey** [comment]
Depends on: #15 #17 #18

**Comment by CHEUNG-K-Jeffrey** [comment]
The other pull requests were closed since it creates more merge conflicts that can’t be easily fixed in one place.

**Review by Pisotski — COMMENTED** [review]
A Code looks like a code. I just don't know what I'm checking. I need assistance from mentors. @Angry-Bob @achasek @cartyz

**Comment by Angry-Bob** [comment]
I have never worked with MSW, but would there be a way to create the mock API on your local machine and make the test call to your mock server? Again, I have never worked with MSW or any mock API, yet. I really haven't ever worked at a scale that required using one.

**Comment by CHEUNG-K-Jeffrey** [comment]
To run it with the mock server
```
$ npm run dev:msw
```

**Comment by CHEUNG-K-Jeffrey** [comment]
> I have never worked with MSW, but would there be a way to create the mock API on your local machine and make the test call to your mock server? Again, I have never worked with MSW or any mock API, yet. I really haven't ever worked at a scale that required using one.

Yes, that should be possible with 186671f.

**Review by Pisotski — APPROVED** [review]

**Pull request merged**
